config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  
  devise_for :admin_users
  devise_for :users
  resources :expenses
  resources :admin_user_expenses

  get 'admin_user_reports', to: 'admin_user_reports#index'
  get 'reports', to: 'reports#index'
  get 'other_expenses', to: 'admin_user_expenses#other_expenses'

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :admin_user_expenses, dependent: :destroy
end

app/models/admin_user_expense.rb
class AdminUserExpense < ApplicationRecord
	belongs_to :admin_user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expense.rb
class Expense < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :expenses, dependent: :destroy
end

app/controllers/admin_user_expenses_controller.rb
class AdminUserExpensesController < ApplicationController
  def index
  	@admin_user_expenses = current_admin_user.admin_user_expenses
  end

  def new 
    @admin_user_expense = AdminUserExpense.new
  end
	
	def show
		@admin_user_expense = AdminUserExpense.find(params[:id])
	end
	
	def edit
		@admin_user_expense = AdminUserExpense.find(params[:id])
	end
	
	def create
		@admin_user_expense = AdminUserExpense.new(admin_user_expense_params)
		@admin_user_expense.admin_user_id = current_admin_user.id
 
		if @admin_user_expense.save
			respond_to do |format|
				flash[:success] = 'Todo was successfully created.'
				format.html { redirect_to @admin_user_expense }
			end
		else
			render 'new'
		end
	end
	
	def update
		@admin_user_expense = AdminUserExpense.find(params[:id])

		if @admin_user_expense.update(admin_user_expense_params)
			respond_to do |format|
				flash[:success] = 'Todo was successfully updated.'
				format.html { redirect_to @admin_user_expense }
			end
		else
			render 'edit'
		end
	end
	
	def destroy
		@admin_user_expense = AdminUserExpense.find(params[:id])
		@admin_user_expense.destroy

		redirect_to admin_user_expenses_path
	end
	
  private 

    def admin_user_expense_params
      params.require(:admin_user_expense).permit(:description, :amount)
    end
end

app/controllers/admin_user_reports_controller.rb
class AdminUserReportsController < ApplicationController
  def index
  	@admin_user_expenses = current_admin_user.admin_user_expenses.where(nil).order('created_at asc')
  	@admin_user_day_report = current_admin_user.admin_user_expenses.group("DATE_TRUNC('week', created_at)").sum(:amount)
  
		if params[:filter_by].present?
			if params[:filter_by][:start_date].present? && params[:filter_by][:end_date].present?
				start_date = Date.new(params[:filter_by][:start_date][0].to_i, params[:filter_by][:start_date][1].to_i, params[:filter_by][:start_date][2].to_i)
				end_date = Date.new(params[:filter_by][:end_date][0].to_i, params[:filter_by][:end_date][1].to_i, params[:filter_by][:end_date][2].to_i)
				Rails.logger.debug start_date
				Rails.logger.debug end_date
				@admin_user_expenses = current_admin_user.admin_user_expenses.where("created_at between (?) and (?)", start_date.to_time, end_date.to_time)
			end
		end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def index
  	@expenses = current_user.expenses

  end

  def new 
    @expense = Expense.new
  end
	
	def show
		@expense = Expense.find(params[:id])
	end
	
	def edit
		@expense = Expense.find(params[:id])
	end
	
	def create
		@expense = Expense.new(expense_params)
		@expense.user_id = current_user.id
 
		if @expense.save
			respond_to do |format|
				flash[:success] = 'Todo was successfully created.'
				format.html { redirect_to @expense }
			end
		else
			render 'new'
		end
	end
	
	def update
		@expense = Expense.find(params[:id])

		if @expense.update(expense_params)
			respond_to do |format|
				flash[:success] = 'Todo was successfully updated.'
				format.html { redirect_to @expense }
			end
		else
			render 'edit'
		end
	end
	
	def destroy
		@expense = Expense.find(params[:id])
		@expense.destroy

		redirect_to expenses_path
	end
	
  private 

    def expense_params
      params.require(:expense).permit(:description, :amount)
    end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
  	@expenses = current_user.expenses.where(nil).order('created_at asc')
  	@day_report = current_user.expenses.group("DATE_TRUNC('week', created_at)").sum(:amount)

		if params[:filter_by].present?
			if params[:filter_by][:start_date].present? && params[:filter_by][:end_date].present?
				start_date = Date.new(params[:filter_by][:start_date][0].to_i, params[:filter_by][:start_date][1].to_i, params[:filter_by][:start_date][2].to_i)
				end_date = Date.new(params[:filter_by][:end_date][0].to_i, params[:filter_by][:end_date][1].to_i, params[:filter_by][:end_date][2].to_i)
				Rails.logger.debug start_date
				Rails.logger.debug end_date
				@expenses = current_user.expenses.where("created_at between (?) and (?)", start_date.to_time, end_date.to_time)
			end
		end
		
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/admin_user_expenses_helper.rb
module AdminUserExpensesHelper
end

app/helpers/admin_user_reports_helper.rb
module AdminUserReportsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin_user_expenses/_form.html.erb
<%= form_for(@admin_user_expense, remote: true) do |f| %>
  <div>
    <%= f.text_field :description, label: false, placeholder: "Description" %>
  </div><br/>

  <div>
    <%= f.text_field :amount, label: false, placeholder: "Amount" %>
  </div><br/>

  <div>
    <%= f.submit %>
  </div>
  
<% end %>

app/views/admin_user_expenses/edit.html.erb
<div style="margin-left: 10px;">
	<h1>Editing Expense</h1>

	<%= render 'form' %><br/>

	<%= link_to 'Back', admin_user_expenses_path %>
	
</div>

app/views/admin_user_expenses/index.html.erb
<div style="margin-left: 10px;">
  <table>
    <tr>
      <h1>Expense</h1>
      <p>Admin User: <%= current_admin_user.email %></p>
    </tr>
   
    <% @admin_user_expenses.each do |admin_user_expense| %>
      <tr>
        <td><%= admin_user_expense.description %></td>
        <td><%= number_to_currency(admin_user_expense.amount) %></td>
        <td><%= admin_user_expense.created_at.strftime("%m/%d/%y %H:%M") %></td>
        <td><%= button_to 'Edit', edit_admin_user_expense_path(admin_user_expense), :method => :get %></td>
        <td><%= button_to 'Delete', admin_user_expense_path(admin_user_expense), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

  </table><br/>

  <%= link_to new_admin_user_expense_path do %>
    <i></i> New Expense
  <% end %>
  <br/>
  <br/>

  <%= link_to 'Homepage', controller: 'welcome' %>
  
</div>

app/views/admin_user_expenses/new.html.erb
<div style="margin-left: 10px;">
	<h1>Creating Expense</h1>

	<%= render 'form' %><br/>

	<%= link_to 'Back', admin_user_expenses_path %>
	
</div>

app/views/admin_user_expenses/other_expenses.html.erb
<div style="margin-left: 10px;">
  <h3>Other Users' Expense Records:</h3>

  <% User.all.each do |user| %>
    <h4>User Account: </h4> 
    <p><%= user.email %> </p>
    <h4>Expense Records: </h4>

    <table>
      <% user.expenses.each do |expense| %>
        <tr>
          <td><%= expense.description %></td>
          <td><%= number_to_currency(expense.amount) %></td>
          <td><%= expense.created_at.strftime("%m/%d/%y %H:%M") %></td>
        </tr>
      <% end %>
    </table>
    
    <br/>
  <% end %>
  <br/>

  <%= link_to 'Homepage', controller: 'welcome' %>

</div>

app/views/admin_user_expenses/show.html.erb
<div style="margin-left: 10px;">
	<h1>Expense Details</h1>

	<p>
	  <strong>Description:</strong>
	  <%= @admin_user_expense.description %>
	</p>

	<p>
	  <strong>Amount:</strong>
	  <%= number_to_currency(@admin_user_expense.amount) %>
	</p>

	<p>
	  <strong>Datetime:</strong>
	  <%= @admin_user_expense.created_at %>
	</p>

	<%= link_to 'Edit', edit_admin_user_expense_path(@admin_user_expense) %> |
	<%= link_to 'Back', admin_user_expenses_path %>
	
</div>

app/views/admin_user_reports/_admin_expense_detail.html.erb
<div id="admin_expense_list">
	<% @admin_user_expenses.each do |admin_user_expense| %>
		<table>
		  <tr>
		    <td><%= admin_user_expense.description %></td>
		    <td><%= number_to_currency(admin_user_expense.amount) %></td>
		    <td><%= admin_user_expense.created_at.strftime("%m/%d/%y %H:%M") %></td>
		  </tr>
		</table>
	<% end %>
</div>

app/views/admin_user_reports/index.html.erb
<div style="margin-left: 10px;">
  <table>
    <tr>
      <h1>Expense</h1>
      <h4>Admin User:</h4>  
      <p><%= current_admin_user.email %></p>
    </tr>

    <h4>Total Amount Spent Per Week: </h4>
    <% @admin_user_day_report.each do |key, value| %>
      <tr>
        <td><%= key.strftime("%m/%d/%y") %> to <%= (key + 7.days).strftime("%m/%d/%y") %></td>
        <td><%= number_to_currency(value) %></td>
      </tr>
    <% end %>

  </table><br/>

  <h3>Expense Records:</h3>
  <%= render "admin_expense_detail" %>

  <%= form_tag admin_user_reports_path(), method: :get do |f| %>
  	<h4>Select date range:</h4>
  	<%= date_select("start_date" , "all_dates", :start_year => 2010, :end_year => 2017, :order => [:month, :day, :year], :use_short_month => true ) %>
    <span>to</span>
    <%= date_select("end_date" , "all_dates", :start_year => 2010, :end_year => 2017, :order => [:month, :day, :year], :use_short_month => true ) %>
    
    <%= link_to admin_user_reports_path(), id: 'admin_search_date_submit' do %>
      <button type="button">SEARCH</button>
    <% end %>

  <% end %>
  <br/>

  <%= link_to 'Homepage', controller: 'welcome' %>

</div>

<script>
$(document).ready(function() {
	$('#admin_search_date_submit').on('click', function(event) {
    event.preventDefault();
    var start_date = []; 
    var end_date = []; 

    start_date.push($('#start_date_all_dates_1i').find(":selected").val());
    start_date.push($('#start_date_all_dates_2i').find(":selected").val());
    start_date.push($('#start_date_all_dates_3i').find(":selected").val());

    end_date.push($('#end_date_all_dates_1i').find(":selected").val());
    end_date.push($('#end_date_all_dates_2i').find(":selected").val());
    end_date.push($('#end_date_all_dates_3i').find(":selected").val());

    console.log("start_date: ");
    console.log(start_date);
    console.log("end_date: ");
    console.log(end_date);
    
    $.ajax({
      url: '/admin_user_reports',
      type: 'GET',
      dataType: 'script',
      data: {
        filter_by:{
          start_date: start_date, 
          end_date: end_date
        } 
      }
    })
    .done(function() {
      console.log("success");
    })
    .fail(function() {
      console.log("error");
    })
    .always(function() {
      console.log("complete");
    });

  });

});
</script>

app/views/admin_user_reports/index.js.erb
console.log("update with filter");
$("#admin_expense_list").empty();
$("#admin_expense_list").append("<%= j render 'admin_expense_detail' %>");

app/views/admin_users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/expenses/_form.html.erb
<%= form_for(@expense, remote: true) do |f| %>
  <div>
    <%= f.text_field :description, label: false, placeholder: "Description" %>
  </div><br/>

  <div>
    <%= f.text_field :amount, label: false, placeholder: "Amount" %>
  </div><br/>

  <div>
    <%= f.submit %>
  </div>
  
<% end %>

app/views/expenses/edit.html.erb
<div style="margin-left: 10px;">
	<h1>Editing Expense</h1>
	 
	<%= render 'form' %><br/> 

	<%= link_to 'Back', expenses_path %>
	
</div>

app/views/expenses/index.html.erb
<div style="margin-left: 10px;">
  <table>
    <tr>
      <h1>Expenses</h1>
      <p>User: <%= current_user.email %></p>
    </tr>
   
    <% @expenses.each do |expense| %>
      <tr>
        <td><%= expense.description %></td>
        <td><%= number_to_currency(expense.amount) %></td>
        <td><%= expense.created_at.strftime("%m/%d/%y %H:%M") %></td>
        <td><%= button_to 'Edit', edit_expense_path(expense), :method => :get %></td>
        <td><%= button_to 'Delete', expense_path(expense), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    
  </table>
  <br/>

  <%= link_to new_expense_path do %>
    <i></i> New Expense
  <% end %>
  <br/>
  <br/>

  <%= link_to 'Homepage', controller: 'welcome' %>
</div>

app/views/expenses/new.html.erb
<div style="margin-left: 10px;">
	<h1>Creating Expense</h1>

	<%= render 'form' %><br/>
	
	<%= link_to 'Back', expenses_path %>
</div>

app/views/expenses/show.html.erb
<div style="margin-left: 10px;">
	<h1>Expense Details</h1>

	<p>
	  <strong>Description:</strong>
	  <%= @expense.description %>
	</p>

	<p>
	  <strong>Amount:</strong>
	  <%= number_to_currency(@expense.amount)%>
	</p>
	 
	<p>
	  <strong>Datetime:</strong>
	  <%= @expense.created_at %>
	</p>

	<%= link_to 'Edit', edit_expense_path(@expense) %> |
	<%= link_to 'Back', expenses_path %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ExpenseTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reports/_expense_detail.html.erb
<div id="expense_list">
	<% @expenses.each do |expense| %>
		<table>
		  <tr>
		    <td><%= expense.description %></td>
		    <td><%= number_to_currency(expense.amount) %></td>
		    <td><%= expense.created_at.strftime("%m/%d/%y %H:%M") %></td>
		  </tr>
		</table>
	<% end %>
</div>

app/views/reports/index.html.erb
<div style="margin-left: 10px;">
  <table>
    <tr>
      <h1>Expense Report</h1>
      <h4>User:</h4> 
      <p><%= current_user.email %></p>
    </tr>

    <h4>Total Amount Spent Per Week: </h4>
    <% @day_report.each do |key, value| %>
      <tr>
        <td><%= key.strftime("%m/%d/%y") %> to <%= (key + 7.days).strftime("%m/%d/%y") %></td>
        <td><%= number_to_currency(value) %></td>
      </tr>
    <% end %>

  </table>
  <br/>

  <h3>Expense Records:</h3>
  <%= render "expense_detail" %>
  <br/>

  <%= form_tag reports_path(), method: :get do |f| %>

  	<h4>Select date range:</h4>
  	<%= date_select("start_date" , "all_dates", :start_year => 2010, :end_year => 2017, :order => [:month, :day, :year], :use_short_month => true ) %>
    <span>to</span>
    <%= date_select("end_date" , "all_dates", :start_year => 2010, :end_year => 2017, :order => [:month, :day, :year], :use_short_month => true ) %>
    
    <%= link_to reports_path(), id: 'search_date_submit' do %>
      <button type="button">SEARCH</button>
    <% end %>

  <% end %>
  <br/>

  <%= link_to 'Homepage', controller: 'welcome' %>

</div>

<script>
$(document).ready(function() {
	$('#search_date_submit').on('click', function(event) {
    event.preventDefault();
    var start_date = []; 
    var end_date = []; 

    start_date.push($('#start_date_all_dates_1i').find(":selected").val());
    start_date.push($('#start_date_all_dates_2i').find(":selected").val());
    start_date.push($('#start_date_all_dates_3i').find(":selected").val());

    end_date.push($('#end_date_all_dates_1i').find(":selected").val());
    end_date.push($('#end_date_all_dates_2i').find(":selected").val());
    end_date.push($('#end_date_all_dates_3i').find(":selected").val());

    console.log("start_date: ");
    console.log(start_date);
    console.log("end_date: ");
    console.log(end_date);
    
    $.ajax({
      url: '/reports',
      type: 'GET',
      dataType: 'script',
      data: {
        filter_by:{
          start_date: start_date, 
          end_date: end_date
        } 
      }
    })
    .done(function() {
      console.log("success");
    })
    .fail(function() {
      console.log("error");
    })
    .always(function() {
      console.log("complete");
    });

  });

});
</script>

app/views/reports/index.js.erb
console.log("update with filter");
$("#expense_list").empty();
$("#expense_list").append("<%= j render 'expense_detail' %>");

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<div style="margin-left: 10px;">
	<h1>Welcome to ExpenseTracker!</h1></br>
	<% if user_signed_in? %>
		<%= link_to 'Go to expenses', expenses_path %></br>
		<%= link_to 'Go to report', reports_path %></br>
		<%= link_to 'Log Out', destroy_user_session_path, method: :delete, :class => "sign_out_link" %>
	<% elsif admin_user_signed_in? %>
		<%= link_to 'Go to expenses', admin_user_expenses_path %></br>
		<%= link_to 'Go to report', admin_user_reports_path %></br>
		<%= link_to 'Check expenses of other users', other_expenses_path %></br>
		<%= link_to 'Log Out', destroy_admin_user_session_path, method: :delete, :class => "sign_out_link" %>
	 <% else %>
	 	<%= link_to "Regular User Log in", new_user_session_url %></br></br>
	 	<%= link_to "Admin User Log in", new_admin_user_session_url %>
	<% end %>
</div>